/*! =========================================================
* bootstrap-slider.js
*
* Maintainers:
* Kyle Kemp
* - Twitter: @seiyria
* - Github: seiyria
* Rohit Kalkur
* - Twitter: @Rovolutionary
* - Github: rovolution
*
* =========================================================
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
* ========================================================= */(function(root,factory){if(typeof define==="function"&&define.amd){define(["jquery"],factory);}
else if(typeof module==="object"&&module.exports){var jQuery;try{jQuery=require("jquery");}
catch(err){jQuery=null;}
module.exports=factory(jQuery);}
else{root.Slider=factory(root.jQuery);}}(this,function($){var Slider;(function($){'use strict';var slice=Array.prototype.slice;function noop(){}
function defineBridget($){if(!$){return;}
function addOptionMethod(PluginClass){if(PluginClass.prototype.option){return;}
PluginClass.prototype.option=function(opts){if(!$.isPlainObject(opts)){return;}
this.options=$.extend(true,this.options,opts);};}
var logError=typeof console==='undefined'?noop:function(message){console.error(message);};function bridge(namespace,PluginClass){$.fn[namespace]=function(options){if(typeof options==='string'){var args=slice.call(arguments,1);for(var i=0,len=this.length;i<len;i++){var elem=this[i];var instance=$.data(elem,namespace);if(!instance){logError("cannot call methods on "+namespace+" prior to initialization; "+
"attempted to call '"+options+"'");continue;}
if(!$.isFunction(instance[options])||options.charAt(0)==='_'){logError("no such method '"+options+"' for "+namespace+" instance");continue;}
var returnValue=instance[options].apply(instance,args);if(returnValue!==undefined&&returnValue!==instance){return returnValue;}}
return this;}else{var objects=this.map(function(){var instance=$.data(this,namespace);if(instance){instance.option(options);instance._init();}else{instance=new PluginClass(this,options);$.data(this,namespace,instance);}
return $(this);});if(!objects||objects.length>1){return objects;}else{return objects[0];}}};}
$.bridget=function(namespace,PluginClass){addOptionMethod(PluginClass);bridge(namespace,PluginClass);};return $.bridget;}
defineBridget($);})($);(function($){var ErrorMsgs={formatInvalidInputErrorMsg:function(input){return "Invalid input value '"+input+"' passed in";},callingContextNotSliderInstance:"Calling context element does not have instance of Slider bound to it. Check your code to make sure the JQuery object returned from the call to the slider() initializer is calling the method"};var SliderScale={linear:{toValue:function(percentage){var rawValue=percentage/100*(this.options.max-this.options.min);if(this.options.ticks_positions.length>0){var minv,maxv,minp,maxp=0;for(var i=0;i<this.options.ticks_positions.length;i++){if(percentage<=this.options.ticks_positions[i]){minv=(i>0)?this.options.ticks[i-1]:0;minp=(i>0)?this.options.ticks_positions[i-1]:0;maxv=this.options.ticks[i];maxp=this.options.ticks_positions[i];break;}}
if(i>0){var partialPercentage=(percentage-minp)/(maxp-minp);rawValue=minv+partialPercentage*(maxv-minv);}}
var value=this.options.min+Math.round(rawValue/this.options.step)*this.options.step;if(value<this.options.min){return this.options.min;}else if(value>this.options.max){return this.options.max;}else{return value;}},toPercentage:function(value){if(this.options.max===this.options.min){return 0;}
if(this.options.ticks_positions.length>0){var minv,maxv,minp,maxp=0;for(var i=0;i<this.options.ticks.length;i++){if(value<=this.options.ticks[i]){minv=(i>0)?this.options.ticks[i-1]:0;minp=(i>0)?this.options.ticks_positions[i-1]:0;maxv=this.options.ticks[i];maxp=this.options.ticks_positions[i];break;}}
if(i>0){var partialPercentage=(value-minv)/(maxv-minv);return minp+partialPercentage*(maxp-minp);}}
return 100*(value-this.options.min)/(this.options.max-this.options.min);}},logarithmic:{toValue:function(percentage){var min=(this.options.min===0)?0:Math.log(this.options.min);var max=Math.log(this.options.max);var value=Math.exp(min+(max-min)*percentage/100);value=this.options.min+Math.round((value-this.options.min)/this.options.step)*this.options.step;if(value<this.options.min){return this.options.min;}else if(value>this.options.max){return this.options.max;}else{return value;}},toPercentage:function(value){if(this.options.max===this.options.min){return 0;}else{var max=Math.log(this.options.max);var min=this.options.min===0?0:Math.log(this.options.min);var v=value===0?0:Math.log(value);return 100*(v-min)/(max-min);}}}};Slider=function(element,options){createNewSlider.call(this,element,options);return this;};function createNewSlider(element,options){this._state={value:null,enabled:null,offset:null,size:null,percentage:null,inDrag:false,over:false};if(typeof element==="string"){this.element=document.querySelector(element);}else if(element instanceof HTMLElement){this.element=element;}
options=options?options:{};var optionTypes=Object.keys(this.defaultOptions);for(var i=0;i<optionTypes.length;i++){var optName=optionTypes[i];var val=options[optName];val=(typeof val!=='undefined')?val:getDataAttrib(this.element,optName);val=(val!==null)?val:this.defaultOptions[optName];if(!this.options){this.options={};}
this.options[optName]=val;}
if(this.options.orientation==="vertical"&&(this.options.tooltip_position==="top"||this.options.tooltip_position==="bottom")){this.options.tooltip_position="right";}
else if(this.options.orientation==="horizontal"&&(this.options.tooltip_position==="left"||this.options.tooltip_position==="right")){this.options.tooltip_position="top";}
function getDataAttrib(element,optName){var dataName="data-slider-"+optName.replace(/_/g,'-');var dataValString=element.getAttribute(dataName);try{return JSON.parse(dataValString);}
catch(err){return dataValString;}}
var origWidth=this.element.style.width;var updateSlider=false;var parent=this.element.parentNode;var sliderTrackSelection;var sliderTrackLow,sliderTrackHigh;var sliderMinHandle;var sliderMaxHandle;if(this.sliderElem){updateSlider=true;}else{this.sliderElem=document.createElement("div");this.sliderElem.className="slider";var sliderTrack=document.createElement("div");sliderTrack.className="slider-track";sliderTrackLow=document.createElement("div");sliderTrackLow.className="slider-track-low";sliderTrackSelection=document.createElement("div");sliderTrackSelection.className="slider-selection";sliderTrackHigh=document.createElement("div");sliderTrackHigh.className="slider-track-high";sliderMinHandle=document.createElement("div");sliderMinHandle.className="slider-handle min-slider-handle";sliderMinHandle.setAttribute('role','slider');sliderMinHandle.setAttribute('aria-valuemin',this.options.min);sliderMinHandle.setAttribute('aria-valuemax',this.options.max);sliderMaxHandle=document.createElement("div");sliderMaxHandle.className="slider-handle max-slider-handle";sliderMaxHandle.setAttribute('role','slider');sliderMaxHandle.setAttribute('aria-valuemin',this.options.min);sliderMaxHandle.setAttribute('aria-valuemax',this.options.max);sliderTrack.appendChild(sliderTrackLow);sliderTrack.appendChild(sliderTrackSelection);sliderTrack.appendChild(sliderTrackHigh);var isLabelledbyArray=Array.isArray(this.options.labelledby);if(isLabelledbyArray&&this.options.labelledby[0]){sliderMinHandle.setAttribute('aria-labelledby',this.options.labelledby[0]);}
if(isLabelledbyArray&&this.options.labelledby[1]){sliderMaxHandle.setAttribute('aria-labelledby',this.options.labelledby[1]);}
if(!isLabelledbyArray&&this.options.labelledby){sliderMinHandle.setAttribute('aria-labelledby',this.options.labelledby);sliderMaxHandle.setAttribute('aria-labelledby',this.options.labelledby);}
this.ticks=[];if(Array.isArray(this.options.ticks)&&this.options.ticks.length>0){for(i=0;i<this.options.ticks.length;i++){var tick=document.createElement('div');tick.className='slider-tick';this.ticks.push(tick);sliderTrack.appendChild(tick);}
sliderTrackSelection.className+=" tick-slider-selection";}
sliderTrack.appendChild(sliderMinHandle);sliderTrack.appendChild(sliderMaxHandle);this.tickLabels=[];if(Array.isArray(this.options.ticks_labels)&&this.options.ticks_labels.length>0){this.tickLabelContainer=document.createElement('div');this.tickLabelContainer.className='slider-tick-label-container';for(i=0;i<this.options.ticks_labels.length;i++){var label=document.createElement('div');var noTickPositionsSpecified=this.options.ticks_positions.length===0;var tickLabelsIndex=(this.options.reversed&&noTickPositionsSpecified)?(this.options.ticks_labels.length-(i+1)):i;label.className='slider-tick-label';label.innerHTML=this.options.ticks_labels[tickLabelsIndex];this.tickLabels.push(label);this.tickLabelContainer.appendChild(label);}}
var createAndAppendTooltipSubElements=function(tooltipElem){var arrow=document.createElement("div");arrow.className="tooltip-arrow";var inner=document.createElement("div");inner.className="tooltip-inner";tooltipElem.appendChild(arrow);tooltipElem.appendChild(inner);};var sliderTooltip=document.createElement("div");sliderTooltip.className="tooltip tooltip-main";sliderTooltip.setAttribute('role','presentation');createAndAppendTooltipSubElements(sliderTooltip);var sliderTooltipMin=document.createElement("div");sliderTooltipMin.className="tooltip tooltip-min";sliderTooltipMin.setAttribute('role','presentation');createAndAppendTooltipSubElements(sliderTooltipMin);var sliderTooltipMax=document.createElement("div");sliderTooltipMax.className="tooltip tooltip-max";sliderTooltipMax.setAttribute('role','presentation');createAndAppendTooltipSubElements(sliderTooltipMax);this.sliderElem.appendChild(sliderTrack);this.sliderElem.appendChild(sliderTooltip);this.sliderElem.appendChild(sliderTooltipMin);this.sliderElem.appendChild(sliderTooltipMax);if(this.tickLabelContainer){this.sliderElem.appendChild(this.tickLabelContainer);}
parent.insertBefore(this.sliderElem,this.element);this.element.style.display="none";}
if($){this.$element=$(this.element);this.$sliderElem=$(this.sliderElem);}
this.eventToCallbackMap={};this.sliderElem.id=this.options.id;this.touchCapable='ontouchstart'in window||(window.DocumentTouch&&document instanceof window.DocumentTouch);this.tooltip=this.sliderElem.querySelector('.tooltip-main');this.tooltipInner=this.tooltip.querySelector('.tooltip-inner');this.tooltip_min=this.sliderElem.querySelector('.tooltip-min');this.tooltipInner_min=this.tooltip_min.querySelector('.tooltip-inner');this.tooltip_max=this.sliderElem.querySelector('.tooltip-max');this.tooltipInner_max=this.tooltip_max.querySelector('.tooltip-inner');if(SliderScale[this.options.scale]){this.options.scale=SliderScale[this.options.scale];}
if(updateSlider===true){this._removeClass(this.sliderElem,'slider-horizontal');this._removeClass(this.sliderElem,'slider-vertical');this._removeClass(this.tooltip,'hide');this._removeClass(this.tooltip_min,'hide');this._removeClass(this.tooltip_max,'hide');["left","top","width","height"].forEach(function(prop){this._removeProperty(this.trackLow,prop);this._removeProperty(this.trackSelection,prop);this._removeProperty(this.trackHigh,prop);},this);[this.handle1,this.handle2].forEach(function(handle){this._removeProperty(handle,'left');this._removeProperty(handle,'top');},this);[this.tooltip,this.tooltip_min,this.tooltip_max].forEach(function(tooltip){this._removeProperty(tooltip,'left');this._removeProperty(tooltip,'top');this._removeProperty(tooltip,'margin-left');this._removeProperty(tooltip,'margin-top');this._removeClass(tooltip,'right');this._removeClass(tooltip,'top');},this);}
if(this.options.orientation==='vertical'){this._addClass(this.sliderElem,'slider-vertical');this.stylePos='top';this.mousePos='pageY';this.sizePos='offsetHeight';}else{this._addClass(this.sliderElem,'slider-horizontal');this.sliderElem.style.width=origWidth;this.options.orientation='horizontal';this.stylePos='left';this.mousePos='pageX';this.sizePos='offsetWidth';}
this._setTooltipPosition();if(Array.isArray(this.options.ticks)&&this.options.ticks.length>0){this.options.max=Math.max.apply(Math,this.options.ticks);this.options.min=Math.min.apply(Math,this.options.ticks);}
if(Array.isArray(this.options.value)){this.options.range=true;this._state.value=this.options.value;}
else if(this.options.range){this._state.value=[this.options.value,this.options.max];}
else{this._state.value=this.options.value;}
this.trackLow=sliderTrackLow||this.trackLow;this.trackSelection=sliderTrackSelection||this.trackSelection;this.trackHigh=sliderTrackHigh||this.trackHigh;if(this.options.selection==='none'){this._addClass(this.trackLow,'hide');this._addClass(this.trackSelection,'hide');this._addClass(this.trackHigh,'hide');}
this.handle1=sliderMinHandle||this.handle1;this.handle2=sliderMaxHandle||this.handle2;if(updateSlider===true){this._removeClass(this.handle1,'round triangle');this._removeClass(this.handle2,'round triangle hide');for(i=0;i<this.ticks.length;i++){this._removeClass(this.ticks[i],'round triangle hide');}}
var availableHandleModifiers=['round','triangle','custom'];var isValidHandleType=availableHandleModifiers.indexOf(this.options.handle)!==-1;if(isValidHandleType){this._addClass(this.handle1,this.options.handle);this._addClass(this.handle2,this.options.handle);for(i=0;i<this.ticks.length;i++){this._addClass(this.ticks[i],this.options.handle);}}
this._state.offset=this._offset(this.sliderElem);this._state.size=this.sliderElem[this.sizePos];this.setValue(this._state.value);this.handle1Keydown=this._keydown.bind(this,0);this.handle1.addEventListener("keydown",this.handle1Keydown,false);this.handle2Keydown=this._keydown.bind(this,1);this.handle2.addEventListener("keydown",this.handle2Keydown,false);this.mousedown=this._mousedown.bind(this);if(this.touchCapable){this.sliderElem.addEventListener("touchstart",this.mousedown,false);}
this.sliderElem.addEventListener("mousedown",this.mousedown,false);if(this.options.tooltip==='hide'){this._addClass(this.tooltip,'hide');this._addClass(this.tooltip_min,'hide');this._addClass(this.tooltip_max,'hide');}
else if(this.options.tooltip==='always'){this._showTooltip();this._alwaysShowTooltip=true;}
else{this.showTooltip=this._showTooltip.bind(this);this.hideTooltip=this._hideTooltip.bind(this);this.sliderElem.addEventListener("mouseenter",this.showTooltip,false);this.sliderElem.addEventListener("mouseleave",this.hideTooltip,false);this.handle1.addEventListener("focus",this.showTooltip,false);this.handle1.addEventListener("blur",this.hideTooltip,false);this.handle2.addEventListener("focus",this.showTooltip,false);this.handle2.addEventListener("blur",this.hideTooltip,false);}
if(this.options.enabled){this.enable();}else{this.disable();}}
Slider.prototype={_init:function(){},constructor:Slider,defaultOptions:{id:"",min:0,max:10,step:1,precision:0,orientation:'horizontal',value:5,range:false,selection:'before',tooltip:'show',tooltip_split:false,handle:'round',reversed:false,enabled:true,formatter:function(val){if(Array.isArray(val)){return val[0]+" : "+val[1];}else{return val;}},natural_arrow_keys:false,ticks:[],ticks_positions:[],ticks_labels:[],ticks_snap_bounds:0,scale:'linear',focus:false,tooltip_position:null,labelledby:null},getElement:function(){return this.sliderElem;},getValue:function(){if(this.options.range){return this._state.value;}
else{return this._state.value[0];}},setValue:function(val,triggerSlideEvent,triggerChangeEvent){if(!val){val=0;}
var oldValue=this.getValue();this._state.value=this._validateInputValue(val);var applyPrecision=this._applyPrecision.bind(this);if(this.options.range){this._state.value[0]=applyPrecision(this._state.value[0]);this._state.value[1]=applyPrecision(this._state.value[1]);this._state.value[0]=Math.max(this.options.min,Math.min(this.options.max,this._state.value[0]));this._state.value[1]=Math.max(this.options.min,Math.min(this.options.max,this._state.value[1]));}
else{this._state.value=applyPrecision(this._state.value);this._state.value=[Math.max(this.options.min,Math.min(this.options.max,this._state.value))];this._addClass(this.handle2,'hide');if(this.options.selection==='after'){this._state.value[1]=this.options.max;}else{this._state.value[1]=this.options.min;}}
if(this.options.max>this.options.min){this._state.percentage=[this._toPercentage(this._state.value[0]),this._toPercentage(this._state.value[1]),this.options.step*100/(this.options.max-this.options.min)];}else{this._state.percentage=[0,0,100];}
this._layout();var newValue=this.options.range?this._state.value:this._state.value[0];if(triggerSlideEvent===true){this._trigger('slide',newValue);}
if((oldValue!==newValue)&&(triggerChangeEvent===true)){this._trigger('change',{oldValue:oldValue,newValue:newValue});}
this._setDataVal(newValue);return this;},destroy:function(){this._removeSliderEventHandlers();this.sliderElem.parentNode.removeChild(this.sliderElem);this.element.style.display="";this._cleanUpEventCallbacksMap();this.element.removeAttribute("data");if($){this._unbindJQueryEventHandlers();this.$element.removeData('slider');}},disable:function(){this._state.enabled=false;this.handle1.removeAttribute("tabindex");this.handle2.removeAttribute("tabindex");this._addClass(this.sliderElem,'slider-disabled');this._trigger('slideDisabled');return this;},enable:function(){this._state.enabled=true;this.handle1.setAttribute("tabindex",0);this.handle2.setAttribute("tabindex",0);this._removeClass(this.sliderElem,'slider-disabled');this._trigger('slideEnabled');return this;},toggle:function(){if(this._state.enabled){this.disable();}else{this.enable();}
return this;},isEnabled:function(){return this._state.enabled;},on:function(evt,callback){this._bindNonQueryEventHandler(evt,callback);return this;},off:function(evt,callback){if($){this.$element.off(evt,callback);this.$sliderElem.off(evt,callback);}else{this._unbindNonQueryEventHandler(evt,callback);}},getAttribute:function(attribute){if(attribute){return this.options[attribute];}else{return this.options;}},setAttribute:function(attribute,value){this.options[attribute]=value;return this;},refresh:function(){this._removeSliderEventHandlers();createNewSlider.call(this,this.element,this.options);if($){$.data(this.element,'slider',this);}
return this;},relayout:function(){this._layout();return this;},_removeSliderEventHandlers:function(){this.handle1.removeEventListener("keydown",this.handle1Keydown,false);this.handle2.removeEventListener("keydown",this.handle2Keydown,false);if(this.showTooltip){this.handle1.removeEventListener("focus",this.showTooltip,false);this.handle2.removeEventListener("focus",this.showTooltip,false);}
if(this.hideTooltip){this.handle1.removeEventListener("blur",this.hideTooltip,false);this.handle2.removeEventListener("blur",this.hideTooltip,false);}
if(this.showTooltip){this.sliderElem.removeEventListener("mouseenter",this.showTooltip,false);}
if(this.hideTooltip){this.sliderElem.removeEventListener("mouseleave",this.hideTooltip,false);}
this.sliderElem.removeEventListener("touchstart",this.mousedown,false);this.sliderElem.removeEventListener("mousedown",this.mousedown,false);},_bindNonQueryEventHandler:function(evt,callback){if(this.eventToCallbackMap[evt]===undefined){this.eventToCallbackMap[evt]=[];}
this.eventToCallbackMap[evt].push(callback);},_unbindNonQueryEventHandler:function(evt,callback){var callbacks=this.eventToCallbackMap[evt];if(callbacks!==undefined){for(var i=0;i<callbacks.length;i++){if(callbacks[i]===callback){callbacks.splice(i,1);break;}}}},_cleanUpEventCallbacksMap:function(){var eventNames=Object.keys(this.eventToCallbackMap);for(var i=0;i<eventNames.length;i++){var eventName=eventNames[i];this.eventToCallbackMap[eventName]=null;}},_showTooltip:function(){if(this.options.tooltip_split===false){this._addClass(this.tooltip,'in');this.tooltip_min.style.display='none';this.tooltip_max.style.display='none';}else{this._addClass(this.tooltip_min,'in');this._addClass(this.tooltip_max,'in');this.tooltip.style.display='none';}
this._state.over=true;},_hideTooltip:function(){if(this._state.inDrag===false&&this.alwaysShowTooltip!==true){this._removeClass(this.tooltip,'in');this._removeClass(this.tooltip_min,'in');this._removeClass(this.tooltip_max,'in');}
this._state.over=false;},_layout:function(){var positionPercentages;if(this.options.reversed){positionPercentages=[100-this._state.percentage[0],this.options.range?100-this._state.percentage[1]:this._state.percentage[1]];}
else{positionPercentages=[this._state.percentage[0],this._state.percentage[1]];}
this.handle1.style[this.stylePos]=positionPercentages[0]+'%';this.handle1.setAttribute('aria-valuenow',this._state.value[0]);this.handle2.style[this.stylePos]=positionPercentages[1]+'%';this.handle2.setAttribute('aria-valuenow',this._state.value[1]);if(Array.isArray(this.options.ticks)&&this.options.ticks.length>0){var styleSize=this.options.orientation==='vertical'?'height':'width';var styleMargin=this.options.orientation==='vertical'?'marginTop':'marginLeft';var labelSize=this._state.size/(this.options.ticks.length-1);if(this.tickLabelContainer){var extraMargin=0;if(this.options.ticks_positions.length===0){if(this.options.orientation!=='vertical'){this.tickLabelContainer.style[styleMargin]=-labelSize/2+'px';}
extraMargin=this.tickLabelContainer.offsetHeight;}else{for(i=0;i<this.tickLabelContainer.childNodes.length;i++){if(this.tickLabelContainer.childNodes[i].offsetHeight>extraMargin){extraMargin=this.tickLabelContainer.childNodes[i].offsetHeight;}}}
if(this.options.orientation==='horizontal'){this.sliderElem.style.marginBottom=extraMargin+'px';}}
for(var i=0;i<this.options.ticks.length;i++){var percentage=this.options.ticks_positions[i]||this._toPercentage(this.options.ticks[i]);if(this.options.reversed){percentage=100-percentage;}
this.ticks[i].style[this.stylePos]=percentage+'%';this._removeClass(this.ticks[i],'in-selection');if(!this.options.range){if(this.options.selection==='after'&&percentage>=positionPercentages[0]){this._addClass(this.ticks[i],'in-selection');}else if(this.options.selection==='before'&&percentage<=positionPercentages[0]){this._addClass(this.ticks[i],'in-selection');}}else if(percentage>=positionPercentages[0]&&percentage<=positionPercentages[1]){this._addClass(this.ticks[i],'in-selection');}
if(this.tickLabels[i]){this.tickLabels[i].style[styleSize]=labelSize+'px';if(this.options.orientation!=='vertical'&&this.options.ticks_positions[i]!==undefined){this.tickLabels[i].style.position='absolute';this.tickLabels[i].style[this.stylePos]=percentage+'%';this.tickLabels[i].style[styleMargin]=-labelSize/2+'px';}else if(this.options.orientation==='vertical'){this.tickLabels[i].style['marginLeft']=this.sliderElem.offsetWidth+'px';this.tickLabelContainer.style['marginTop']=this.sliderElem.offsetWidth/2*-1+'px';}}}}
var formattedTooltipVal;if(this.options.range){formattedTooltipVal=this.options.formatter(this._state.value);this._setText(this.tooltipInner,formattedTooltipVal);this.tooltip.style[this.stylePos]=(positionPercentages[1]+positionPercentages[0])/2+'%';if(this.options.orientation==='vertical'){this._css(this.tooltip,'margin-top',-this.tooltip.offsetHeight/2+'px');}else{this._css(this.tooltip,'margin-left',-this.tooltip.offsetWidth/2+'px');}
if(this.options.orientation==='vertical'){this._css(this.tooltip,'margin-top',-this.tooltip.offsetHeight/2+'px');}else{this._css(this.tooltip,'margin-left',-this.tooltip.offsetWidth/2+'px');}
var innerTooltipMinText=this.options.formatter(this._state.value[0]);this._setText(this.tooltipInner_min,innerTooltipMinText);var innerTooltipMaxText=this.options.formatter(this._state.value[1]);this._setText(this.tooltipInner_max,innerTooltipMaxText);this.tooltip_min.style[this.stylePos]=positionPercentages[0]+'%';if(this.options.orientation==='vertical'){this._css(this.tooltip_min,'margin-top',-this.tooltip_min.offsetHeight/2+'px');}else{this._css(this.tooltip_min,'margin-left',-this.tooltip_min.offsetWidth/2+'px');}
this.tooltip_max.style[this.stylePos]=positionPercentages[1]+'%';if(this.options.orientation==='vertical'){this._css(this.tooltip_max,'margin-top',-this.tooltip_max.offsetHeight/2+'px');}else{this._css(this.tooltip_max,'margin-left',-this.tooltip_max.offsetWidth/2+'px');}}else{formattedTooltipVal=this.options.formatter(this._state.value[0]);this._setText(this.tooltipInner,formattedTooltipVal);this.tooltip.style[this.stylePos]=positionPercentages[0]+'%';if(this.options.orientation==='vertical'){this._css(this.tooltip,'margin-top',-this.tooltip.offsetHeight/2+'px');}else{this._css(this.tooltip,'margin-left',-this.tooltip.offsetWidth/2+'px');}}
if(this.options.orientation==='vertical'){this.trackLow.style.top='0';this.trackLow.style.height=Math.min(positionPercentages[0],positionPercentages[1])+'%';this.trackSelection.style.top=Math.min(positionPercentages[0],positionPercentages[1])+'%';this.trackSelection.style.height=Math.abs(positionPercentages[0]-positionPercentages[1])+'%';this.trackHigh.style.bottom='0';this.trackHigh.style.height=(100-Math.min(positionPercentages[0],positionPercentages[1])-Math.abs(positionPercentages[0]-positionPercentages[1]))+'%';}
else{this.trackLow.style.left='0';this.trackLow.style.width=Math.min(positionPercentages[0],positionPercentages[1])+'%';this.trackSelection.style.left=Math.min(positionPercentages[0],positionPercentages[1])+'%';this.trackSelection.style.width=Math.abs(positionPercentages[0]-positionPercentages[1])+'%';this.trackHigh.style.right='0';this.trackHigh.style.width=(100-Math.min(positionPercentages[0],positionPercentages[1])-Math.abs(positionPercentages[0]-positionPercentages[1]))+'%';var offset_min=this.tooltip_min.getBoundingClientRect();var offset_max=this.tooltip_max.getBoundingClientRect();if(offset_min.right>offset_max.left){this._removeClass(this.tooltip_max,'top');this._addClass(this.tooltip_max,'bottom');this.tooltip_max.style.top=18+'px';}else{this._removeClass(this.tooltip_max,'bottom');this._addClass(this.tooltip_max,'top');this.tooltip_max.style.top=this.tooltip_min.style.top;}}},_removeProperty:function(element,prop){if(element.style.removeProperty){element.style.removeProperty(prop);}else{element.style.removeAttribute(prop);}},_mousedown:function(ev){if(!this._state.enabled){return false;}
this._state.offset=this._offset(this.sliderElem);this._state.size=this.sliderElem[this.sizePos];var percentage=this._getPercentage(ev);if(this.options.range){var diff1=Math.abs(this._state.percentage[0]-percentage);var diff2=Math.abs(this._state.percentage[1]-percentage);this._state.dragged=(diff1<diff2)?0:1;}else{this._state.dragged=0;}
this._state.percentage[this._state.dragged]=percentage;this._layout();if(this.touchCapable){document.removeEventListener("touchmove",this.mousemove,false);document.removeEventListener("touchend",this.mouseup,false);}
if(this.mousemove){document.removeEventListener("mousemove",this.mousemove,false);}
if(this.mouseup){document.removeEventListener("mouseup",this.mouseup,false);}
this.mousemove=this._mousemove.bind(this);this.mouseup=this._mouseup.bind(this);if(this.touchCapable){document.addEventListener("touchmove",this.mousemove,false);document.addEventListener("touchend",this.mouseup,false);}
document.addEventListener("mousemove",this.mousemove,false);document.addEventListener("mouseup",this.mouseup,false);this._state.inDrag=true;var newValue=this._calculateValue();this._trigger('slideStart',newValue);this._setDataVal(newValue);this.setValue(newValue,false,true);this._pauseEvent(ev);if(this.options.focus){this._triggerFocusOnHandle(this._state.dragged);}
return true;},_triggerFocusOnHandle:function(handleIdx){if(handleIdx===0){this.handle1.focus();}
if(handleIdx===1){this.handle2.focus();}},_keydown:function(handleIdx,ev){if(!this._state.enabled){return false;}
var dir;switch(ev.keyCode){case 37:case 40:dir=-1;break;case 39:case 38:dir=1;break;}
if(!dir){return;}
if(this.options.natural_arrow_keys){var ifVerticalAndNotReversed=(this.options.orientation==='vertical'&&!this.options.reversed);var ifHorizontalAndReversed=(this.options.orientation==='horizontal'&&this.options.reversed);if(ifVerticalAndNotReversed||ifHorizontalAndReversed){dir=-dir;}}
var val=this._state.value[handleIdx]+dir*this.options.step;if(this.options.range){val=[(!handleIdx)?val:this._state.value[0],(handleIdx)?val:this._state.value[1]];}
this._trigger('slideStart',val);this._setDataVal(val);this.setValue(val,true,true);this._setDataVal(val);this._trigger('slideStop',val);this._layout();this._pauseEvent(ev);return false;},_pauseEvent:function(ev){if(ev.stopPropagation){ev.stopPropagation();}
if(ev.preventDefault){ev.preventDefault();}
ev.cancelBubble=true;ev.returnValue=false;},_mousemove:function(ev){if(!this._state.enabled){return false;}
var percentage=this._getPercentage(ev);this._adjustPercentageForRangeSliders(percentage);this._state.percentage[this._state.dragged]=percentage;this._layout();var val=this._calculateValue(true);this.setValue(val,true,true);return false;},_adjustPercentageForRangeSliders:function(percentage){if(this.options.range){var precision=this._getNumDigitsAfterDecimalPlace(percentage);precision=precision?precision-1:0;var percentageWithAdjustedPrecision=this._applyToFixedAndParseFloat(percentage,precision);if(this._state.dragged===0&&this._applyToFixedAndParseFloat(this._state.percentage[1],precision)<percentageWithAdjustedPrecision){this._state.percentage[0]=this._state.percentage[1];this._state.dragged=1;}else if(this._state.dragged===1&&this._applyToFixedAndParseFloat(this._state.percentage[0],precision)>percentageWithAdjustedPrecision){this._state.percentage[1]=this._state.percentage[0];this._state.dragged=0;}}},_mouseup:function(){if(!this._state.enabled){return false;}
if(this.touchCapable){document.removeEventListener("touchmove",this.mousemove,false);document.removeEventListener("touchend",this.mouseup,false);}
document.removeEventListener("mousemove",this.mousemove,false);document.removeEventListener("mouseup",this.mouseup,false);this._state.inDrag=false;if(this._state.over===false){this._hideTooltip();}
var val=this._calculateValue(true);this._layout();this._setDataVal(val);this._trigger('slideStop',val);return false;},_calculateValue:function(snapToClosestTick){var val;if(this.options.range){val=[this.options.min,this.options.max];if(this._state.percentage[0]!==0){val[0]=this._toValue(this._state.percentage[0]);val[0]=this._applyPrecision(val[0]);}
if(this._state.percentage[1]!==100){val[1]=this._toValue(this._state.percentage[1]);val[1]=this._applyPrecision(val[1]);}}else{val=this._toValue(this._state.percentage[0]);val=parseFloat(val);val=this._applyPrecision(val);}
if(snapToClosestTick){var min=[val,Infinity];for(var i=0;i<this.options.ticks.length;i++){var diff=Math.abs(this.options.ticks[i]-val);if(diff<=min[1]){min=[this.options.ticks[i],diff];}}
if(min[1]<=this.options.ticks_snap_bounds){return min[0];}}
return val;},_applyPrecision:function(val){var precision=this.options.precision||this._getNumDigitsAfterDecimalPlace(this.options.step);return this._applyToFixedAndParseFloat(val,precision);},_getNumDigitsAfterDecimalPlace:function(num){var match=(''+num).match(/(?:\.(\d+))?(?:[eE]([+-]?\d+))?$/);if(!match){return 0;}
return Math.max(0,(match[1]?match[1].length:0)-(match[2]?+match[2]:0));},_applyToFixedAndParseFloat:function(num,toFixedInput){var truncatedNum=num.toFixed(toFixedInput);return parseFloat(truncatedNum);},_getPercentage:function(ev){if(this.touchCapable&&(ev.type==='touchstart'||ev.type==='touchmove')){ev=ev.touches[0];}
var eventPosition=ev[this.mousePos];var sliderOffset=this._state.offset[this.stylePos];var distanceToSlide=eventPosition-sliderOffset;var percentage=(distanceToSlide/this._state.size)*100;percentage=Math.round(percentage/this._state.percentage[2])*this._state.percentage[2];if(this.options.reversed){percentage=100-percentage;}
return Math.max(0,Math.min(100,percentage));},_validateInputValue:function(val){if(typeof val==='number'){return val;}else if(Array.isArray(val)){this._validateArray(val);return val;}else{throw new Error(ErrorMsgs.formatInvalidInputErrorMsg(val));}},_validateArray:function(val){for(var i=0;i<val.length;i++){var input=val[i];if(typeof input!=='number'){throw new Error(ErrorMsgs.formatInvalidInputErrorMsg(input));}}},_setDataVal:function(val){this.element.setAttribute('data-value',val);this.element.setAttribute('value',val);this.element.value=val;},_trigger:function(evt,val){val=(val||val===0)?val:undefined;var callbackFnArray=this.eventToCallbackMap[evt];if(callbackFnArray&&callbackFnArray.length){for(var i=0;i<callbackFnArray.length;i++){var callbackFn=callbackFnArray[i];callbackFn(val);}}
if($){this._triggerJQueryEvent(evt,val);}},_triggerJQueryEvent:function(evt,val){var eventData={type:evt,value:val};this.$element.trigger(eventData);this.$sliderElem.trigger(eventData);},_unbindJQueryEventHandlers:function(){this.$element.off();this.$sliderElem.off();},_setText:function(element,text){if(typeof element.innerText!=="undefined"){element.innerText=text;}else if(typeof element.textContent!=="undefined"){element.textContent=text;}},_removeClass:function(element,classString){var classes=classString.split(" ");var newClasses=element.className;for(var i=0;i<classes.length;i++){var classTag=classes[i];var regex=new RegExp("(?:\\s|^)"+classTag+"(?:\\s|$)");newClasses=newClasses.replace(regex," ");}
element.className=newClasses.trim();},_addClass:function(element,classString){var classes=classString.split(" ");var newClasses=element.className;for(var i=0;i<classes.length;i++){var classTag=classes[i];var regex=new RegExp("(?:\\s|^)"+classTag+"(?:\\s|$)");var ifClassExists=regex.test(newClasses);if(!ifClassExists){newClasses+=" "+classTag;}}
element.className=newClasses.trim();},_offsetLeft:function(obj){return obj.getBoundingClientRect().left;},_offsetTop:function(obj){var offsetTop=obj.offsetTop;while((obj=obj.offsetParent)&&!isNaN(obj.offsetTop)){offsetTop+=obj.offsetTop;}
return offsetTop;},_offset:function(obj){return{left:this._offsetLeft(obj),top:this._offsetTop(obj)};},_css:function(elementRef,styleName,value){if($){$.style(elementRef,styleName,value);}else{var style=styleName.replace(/^-ms-/,"ms-").replace(/-([\da-z])/gi,function(all,letter){return letter.toUpperCase();});elementRef.style[style]=value;}},_toValue:function(percentage){return this.options.scale.toValue.apply(this,[percentage]);},_toPercentage:function(value){return this.options.scale.toPercentage.apply(this,[value]);},_setTooltipPosition:function(){var tooltips=[this.tooltip,this.tooltip_min,this.tooltip_max];if(this.options.orientation==='vertical'){var tooltipPos=this.options.tooltip_position||'right';var oppositeSide=(tooltipPos==='left')?'right':'left';tooltips.forEach(function(tooltip){this._addClass(tooltip,tooltipPos);tooltip.style[oppositeSide]='100%';}.bind(this));}else if(this.options.tooltip_position==='bottom'){tooltips.forEach(function(tooltip){this._addClass(tooltip,'bottom');tooltip.style.top=22+'px';}.bind(this));}else{tooltips.forEach(function(tooltip){this._addClass(tooltip,'top');tooltip.style.top=-this.tooltip.outerHeight-14+'px';}.bind(this));}}};if($){var namespace=$.fn.slider?'bootstrapSlider':'slider';$.bridget(namespace,Slider);}})($);return Slider;}));function getInitialFilters(){var region=getParameterByName("region");if(region!=null&&region!=""){$("ul.dropdown-menu.regionMenu li").each(function(){var thisCode=$(this).find("a").first().attr("data-regionCode");if(thisCode==region){var regionName=$(this).find("a").first().attr("data-placeName");$("#selectedRegionButton").html(regionName+' <span class="caret"></span>');$(this).find("a").first().addClass("selected");}});}}
function createFilterObject(){var filterObj=new Object();var selectedCategories=$(".categoryInput:checked");var categoriesString="";if(selectedCategories.length>0){for(var i=0;i<selectedCategories.length;i++){categoriesString=categoriesString+$(selectedCategories[i]).val()+",";}}
var selectedPopularity=$(".popularityInput:checked");var popString="";if(selectedPopularity.length>0){for(var i=0;i<selectedPopularity.length;i++){popString=popString+$(selectedPopularity[i]).val()+",";}}
var selectedBestTime=$(".bestTime:checked");var bestTime=new Array();for(var i=0;i<selectedBestTime.length;i++){bestTime.push($(selectedBestTime[i]).val());}
var bestTimeString="";if(bestTime.length>0){for(var i=1;i<=4;i++){if(bestTime.indexOf(i+"")>=0)bestTimeString+="1";else bestTimeString+="0";}
filterObj.bestTimeVisitBitmap=bestTimeString;}
var selectedActivities=$(".activityInput:checked");var activitiesString="";if(selectedActivities.length>0){for(var i=0;i<selectedActivities.length;i++){activitiesString=activitiesString+$(selectedActivities[i]).val()+",";}}
var distanceSelected=$("#distanceCurrent").text();var nearbyPage=$("#distanceCurrent").length>0;var daysSelected=$("#daysCurrent").text();var selectedElem=$("ul.dropdown-menu.regionMenu li a.selected");var regionCode=$(selectedElem).attr("data-regionCode");var sortBy=$(".refineSortOptions a.active").attr("data-sortBy");var mapBox=$("#mapBox").val();filterObj.categoryTags=categoriesString;filterObj.activityTags=activitiesString;filterObj.popularityTags=popString;if($("#openMapButton").css('display')=='none')
filterObj.mapBox=mapBox;if(nearbyPage)filterObj.distance=distanceSelected;else{filterObj.numberOfDays=daysSelected;filterObj.region=regionCode;}
var sortObject=new Object();sortObject.sortCriterion=sortBy;filterObj.holidifySortObject=sortObject;var selectedVisa=$(".visaInput:checked");var visaString="";if(selectedVisa.length>0){for(var i=0;i<selectedVisa.length;i++){visaString=visaString+$(selectedVisa[i]).val()+",";}}
filterObj.visaCategory=visaString;var selectedBudget=$(".budgetInput:checked");var budgetString="";if(selectedBudget.length>0){for(var i=0;i<selectedBudget.length;i++){budgetString=budgetString+$(selectedBudget[i]).val()+",";}}
filterObj.budgetCategory=budgetString;var selectedFlightPrice=$(".flightPrice:checked");var flightPriceArr=[];$(selectedFlightPrice).each(function(){flightPriceArr.push(parseInt($(this).attr("data-minrate")));flightPriceArr.push(parseInt($(this).attr("data-maxrate")));});if(flightPriceArr.length>0){filterObj.maxFlightPrice=Math.max.apply(Math,flightPriceArr);filterObj.minFlightPrice=Math.min.apply(Math,flightPriceArr);}
console.log(filterObj);return filterObj;}
function getFirstThreeTagsHtml(tags){var tagsHtml="";var allowedTags=["beaches","hills-n-valleys","deserts","wildlife","heritage","religious","rivers-n-lakes","adventure","trekking","water-sports","extreme","snow-sports"];var allTags=tags.toLowerCase().replace("/, /g",",").split(",");for(var i=0;i<allTags.length&&i<3;i++){if(allowedTags.indexOf(allTags[i].toLowerCase())>=0)
tagsHtml+="<a href=\"/lists/"+allTags[i].replace("/ /g","-").replace("&","n")+"\">"+toTitleCase(allTags[i])+"</a>";else
tagsHtml+="<a>"+toTitleCase(allTags[i])+"</a>";}
return tagsHtml;}
function getTripCardHtml(longTrip,placeName){var bgColor=getRatingColor(longTrip.rating);var ratingRound=roundTwoDecimals(longTrip.rating);var introSmall=longTrip.intro;if(introSmall.length>230)introSmall=introSmall.substring(0,230)+"...";var distanceString='';if(placeName!=null)distanceString='<p class="destinationObjective destinationDistance"> '+longTrip.distance+' Kms from '+placeName+' </p>';var tagsHtml=getFirstThreeTagsHtml(longTrip.tags);var longTripHtml='<div class="col-md-6 col-xs-12 resultColumn">'+
'<div class="result">'+
'<a href="/long-trips/'+longTrip.id.toLowerCase()+'">'+
'<img src="/images/patt.png" data-original="'+longTrip.imageUrl+'" class="resultImage lazy" /></a>'+
'<p class="rating" style="background-color:'+bgColor+'">'+ratingRound+'</p>'+
'<p class="destinationObjective destinationTags">'+
'<p class="destinationObjective"><a class="resultName" href="/long-trips/'+longTrip.id.toLowerCase()+'/">'+longTrip.name+'</a></p>'+
'<div class="destinationParameters hidden-xs col-md-12 col-xs-12">'+
'<p class="first"> <span class="dist"><b>'+longTrip.minDays+' - '+longTrip.maxDays+'</b> <br /> Days </span> </p>'+
'<p class="divider">/</p>'+
'<p> <span class="dist"><b>'+longTrip.bestTimeToVisitString+' </b> <br /> Best Time </span> </p>'+
'<p class="divider">/</p>'+
'<p> <span class="dist"><b> '+longTrip.distance+' </b> kms <br /> from '+placeName+' </span> </p>'+
'</div>'+
'<p class="destinationText hidden-xs">'+longTrip.intro+'</p>'+
'<p class="destinationObjective hidden-xs"><a class="readMore" href="/long-trips/'+longTrip.id.toLowerCase()+'/">Read More</a></p> </div></div>';return longTripHtml;}
function getStateCardHtml(state,placeName){var bgColor=getRatingColor(state.rating);var ratingRound=roundTwoDecimals(state.rating);var introSmall=state.intro;if(introSmall.length>230)introSmall=introSmall.substring(0,230)+"...";var distanceString='';if(placeName!=null)distanceString='<p class="destinationObjective destinationDistance"> '+state.distance+' Kms from '+placeName+' </p>';var stateHtml='<div class="col-md-6 col-xs-12 resultColumn">'+
'<div class="result">'+
'<a href="/state/'+state.id.toLowerCase()+'">'+
'<img src="/images/patt.png" data-original="https://www.holidify.com/images/tooltipImages/'+state.id+'.jpg" class="resultImage lazy" /></a>'+
'<p class="rating" style="background-color:'+bgColor+'">'+ratingRound+'</p>'+
'<p class="destinationObjective destinationTags">'+
'<p class="destinationObjective"><a class="resultName" href="/state/'+state.id.toLowerCase()+'/">'+state.name+'</a></p>'+
'<div class="destinationParameters col-md-12 col-xs-12 hidden-xs">'+
'<p class="first"> <span class="dist"><b>'+state.numAttractions+'</b> <br /> Destinations </span> </p>'+
'<p class="divider">/</p>'+
'<p> <span class="dist"><b>'+state.minDays+' - '+state.maxDays+' </b> <br /> Days </span> </p>'+
'<p class="divider">/</p>'+
'<p> <span class="dist"><b> '+state.distance+' </b> kms <br /> from '+placeName+' </span> </p>'+
'</div>'+
'<div class="destinationParameters col-xs-12 visible-xs"> <p> <a href="/list/'+state.id.toLowerCase()+'/"> '+destination.numAttractions+' places to visit </a> </p> </div>'+
'<p class="destinationText hidden-xs">'+state.intro+'</p>'+
'<p class="destinationObjective"><a class="readMore" href="/state/'+state.id.toLowerCase()+'/">Read More</a></p> </div></div>';return stateHtml;}
function getDestinationCardHtml(destination,placeName){var bgColor=getRatingColor(destination.rating);var ratingRound=roundTwoDecimals(destination.rating);var introSmall=destination.intro;if(introSmall.length>230)introSmall=introSmall.substring(0,230)+"...";var distanceString='';if(placeName!=null)distanceString='<p class="destinationObjective destinationDistance"> '+destination.distance+' Kms from '+placeName+' </p>';if(destination.weather!=null){destMin=Math.round((destination.weather.minTemp-32)*5/9);destMax=Math.round((destination.weather.maxTemp-32)*5/9);var weatherHtml='<div class="destinationParameters col-md-12 col-xs-12 hidden-xs">'+
'<p class="first"> <b> Current Weather: <img src="https://www.holidify.com/images/logos/weather-icons/'+destination.weather.icon+'" title="'+destination.weather.icon+'" class="weatherIcon" />'+
destMin+' - '+destMax+'&deg; C </b> <br /> </p></div>';}
var commonHtml1='<div class="col-md-6 col-xs-12 resultColumn">'+
'<div class="result">'+
'<input type="hidden" class="dataHolder" data-url ="/places/'+destination.id.toLowerCase()+'/" data-img="<img src=https://www.holidify.com/images/tooltipImages/'+destination.id+'.jpg class='+'mapDivImg'+'>" data-dist = "'+destination.distance+'" data-name="'+destination.name+' " data-code="'+destination.placeCode+'" data-lat="'+destination.latitude+'" data-lng="'+destination.longitude+'" data-marker="'+destination.mainTag+'" />'+
'<a href="/places/'+destination.id.toLowerCase()+'/">'+
'<img src="/images/patt.png" data-original="https://www.holidify.com/images/tooltipImages/'+destination.id+'.jpg" class="resultImage lazy" /></a>'+
'<p class="rating" style="background-color:'+bgColor+'">'+ratingRound+'</p>'+
'<p class="destinationObjective destinationTags">'+
'<p class="destinationObjective"><a class="resultName" href="/places/'+destination.id.toLowerCase()+'/">'+destination.name+'</a></p>'+
'<div class="destinationParameters col-md-12 col-xs-12 hidden-xs">'+
'<p class="first"> <a href="/places/'+destination.id.toLowerCase()+'/sightseeing-and-things-to-do.html"><b> '+destination.numAttractions+' </b><br /> Things to Do</a> </p>'+
'<p class="divider">/</p>'+
'<p> <span class="dist"><b> '+destination.distance+' </b> kms <br /> from '+placeName+' </span> </p>'+
'</div>';var commonHtml2='<div class="destinationParameters col-xs-12 visible-xs"> <p> <a href="/places/'+destination.id.toLowerCase()+'/sightseeing-and-things-to-do.html"> '+destination.numAttractions+' places to visit </a> </p> </div>'+
'<p class="destinationText hidden-xs">'+destination.intro+'</p>'+
'<p class="destinationObjective"><a class="readMore" href="/places/'+destination.id.toLowerCase()+'/">Read More</a></p> </div></div>';if(destination.weather!=null){var destinationHtml=commonHtml1+weatherHtml+commonHtml2;}
else{var destinationHtml=commonHtml1+commonHtml2;}
return destinationHtml;}
function renderResultsList(results,placeName){var numShown=0;for(var i=0;i<results.length;i++){if(results[i].type=="DESTINATION"&&results[i].distance>10){var destinationHtml=getDestinationCardHtml(results[i],placeName);$("#resultsContainer").append(destinationHtml);numShown++;}
if(results[i].type=="STATE"&&results[i].distance>10){var stateHtml=getStateCardHtml(results[i],placeName);$("#resultsContainer").append(stateHtml);numShown++;}
if(results[i].type=="TRIP"&&results[i].distance>10){var tripHtml=getTripCardHtml(results[i],placeName);$("#resultsContainer").append(tripHtml);numShown++;}
if(numShown>0&&numShown%2==0)$("#resultsContainer").append('<div class="clearfix"></div>');}
if(numShown==0){var noResults='<div class="selectOriginContainer noResultsFound col-md-12 col-xs-12">'+
'<img src="https://www.holidify.com/res/images/wg_generic_bg.jpg" class="bgImage" />'+
'<div class="overlay">'+
'<div class="middleText text-center"> '+
'Sorry, No Results Found <br />'+
'<a href="#" class="clearFilters" onclick="clearAllFilters()"> Clear Filters</a>'+
'</div>'+
'</div>'+
'</div>';$("#resultsContainer").append(noResults);}
$("#numResults").text(numShown+" results found");$("#resultsContainer").show();$("img.resultImage.lazy").lazyload({effect:"fadeIn"});var distanceSelected=$("#distanceCurrent").text();if(parseFloat(distanceSelected)<=300)
initFullWeekendMap(8);else
initFullWeekendMap(7);}
function selectCity(placeCode){$("ul.dropdown-menu.startingPlaceMenu li a").removeClass("selected");$("#selectedPlaceButton").html("Places Near "+toTitleCase(placeCode)+' <span class="caret"></span>');$("ul.dropdown-menu.startingPlaceMenu li a").each(function(){if($(this).attr("data-placeCode")==placeCode)$(this).addClass("selected");});if(placeCode!="ME"){var appendUrl="from-"+placeCode.toLowerCase()+".html";history.pushState("","",appendUrl);}
getDestinationsList();}
function readCurrentLocation(){if(navigator.geolocation){navigator.geolocation.getCurrentPosition(function(position){var currentLatitude=position.coords.latitude;var currentLongitude=position.coords.longitude;var currentLocationName="";$("#nearMeDataHolder").attr("data-lat",currentLatitude);$("#nearMeDataHolder").attr("data-lng",currentLongitude);selectCity("ME");return;var latlng=new google.maps.LatLng(currentLatitude,currentLongitude);var geocoder=new google.maps.Geocoder();geocoder.geocode({'latLng':latlng},function(results,status){if(status==google.maps.GeocoderStatus.OK){if(results[1]){for(var j=0;j<results.length;j++){if(results[j].types[0]=="locality")currentLocationName=results[j].address_components[0].short_name;}
if(currentLocationName.indexOf("Delhi")>=0){selectCity("DELHI");}
else if(currentLocationName.toLowerCase().indexOf("noida")>=0){selectCity("DELHI");}
else if(currentLocationName.toLowerCase().indexOf("gurgaon")>=0){selectCity("DELHI");}
else if(currentLocationName.indexOf("Mumbai")>=0){selectCity("DELHI");}
else if(currentLocationName.indexOf("Pune")>=0){selectCity("DELHI");}
else if(currentLocationName.indexOf("Kolkata")>=0){selectCity("DELHI");}
else if(currentLocationName.indexOf("Bangalore")>=0){selectCity("DELHI");}
else if(currentLocationName.indexOf("Hyderabad")>=0){selectCity("DELHI");}
else if(currentLocationName.indexOf("Chennai")>=0){selectCity("DELHI");}
else if(currentLocationName.indexOf("Chandigarh")>=0){selectCity("DELHI");}
else if(currentLocationName.indexOf("Ahmedabad")>=0){selectCity("DELHI");}
else if(currentLocationName.indexOf("Jaipur")>=0){selectCity("DELHI");}
else if(currentLocationName.indexOf("Guwahati")>=0){selectCity("DELHI");}
else if(currentLocationName.indexOf("Bhopal")>=0){selectCity("DELHI");}}}else{}});},function(error){showNotification("Sorry, unable to detect your location. You can set your location via...");},{timeout:5000});}
else{}}
function enableSlider(){if($("#ex1").length>0){$('#ex1').slider({formatter:function(value){return 'Distance upto '+value+' kms';},tooltip:"hide"});$("#ex1").slider().on("change",function(object){$("#distanceCurrent").text(object.value.newValue);});$("#ex1").slider().on("slideStop",function(object){trackGAEvent("FilterTracking","FilterPressed","DistanceChanged");getDestinationsList();});}else{$('#ex2').slider({formatter:function(value){return 'Trip Duration '+value+' days';},tooltip:"hide"});$("#ex2").slider().on("change",function(object){$("#daysCurrent").text(object.value.newValue);});$("#ex2").slider().on("slideStop",function(object){getDestinationsList();});}}
function enableFilters(){$("#showFilters").click(function(){if($("#allFiltersContainer").hasClass("hidden-xs")||$("#allFiltersContainer").hasClass("hidden-sm")){$("#allFiltersContainer").removeClass("hidden-xs");$("#allFiltersContainer").removeClass("hidden-sm");}else{$("#allFiltersContainer").addClass("hidden-xs");$("#allFiltersContainer").addClass("hidden-sm");}});$("#showMobileFilters").click(function(){$(".filterPopupContainer").show();$("body").css("overflow-y","hidden");});$(".hideMobileFilters").click(function(){$(".filterPopupContainer").hide();$("body").css("overflow-y","scroll");});$("a.btn.filterButton").click(function(){$(this).toggleClass("activated");getDestinationsList();});$("a.sortOption").click(function(){trackGAEvent("FilterTracking","SortBY",this.text);$("a.sortOption").removeClass("active");$(this).addClass("active");getDestinationsList();});$("ul.dropdown-menu.startingPlaceMenu li").click(function(){var clickedText=$(this).find("a").first().text();trackGAEvent("FilterTracking","DestinationChanged",clickedText);$("ul.dropdown-menu.startingPlaceMenu li a").removeClass("selected");$(this).find("a").first().addClass("selected");$("#selectedPlaceButton").html(clickedText+' <span class="caret"></span>');getDestinationsList();});$(".roundedTwo input").click(function(){var thisId=$(this).attr("id");trackGAEvent("FilterTracking","FilterPressed",thisId);var currentStatus=$($("input[id='"+thisId+"']")[1]).prop("checked");$("input[id='"+thisId+"']").prop("checked",!currentStatus);getDestinationsList();});$(".roundedTwo .marginSet").click(function(e){e.preventDefault();var thisId=$(this).attr("data-for");$("input[id='"+thisId+"']").prop("checked",!$("#"+thisId).prop("checked"));getDestinationsList();return false;});}
function clearAllFilters(){trackGAEvent("FilterTracking","FilterPressed","filterCleared");$(".categoryInput").attr("checked",false);$(".activityInput").attr("checked",false);$(".bestTime").attr("checked",false);$(".popularityInput").attr("checked",false);if($("#ex1").length>0){$("#ex1").slider('setValue',500);$("#distanceCurrent").text("500");}else if($("#ex2").length>0){$("#ex2").slider('setValue',3);$("#daysCurrent").text("3");}
getDestinationsList();}
function enableSelectOriginDialogue(){$("ul.dropdown-menu.selectOriginMenu li").click(function(){var clickedText=$(this).find("a").first().text();var clickedCode=$(this).find("a").first().attr("data-placeCode");$("#selectedPlaceButton").html(clickedText+' <span class="caret"></span>');$("ul.dropdown-menu.startingPlaceMenu li a").each(function(){if($(this).attr("data-placeCode")==clickedCode)$(this).addClass("selected");});var appendUrl="from-"+clickedCode.toLowerCase()+".html";history.pushState("","",appendUrl);getDestinationsList();});}
function enableSelectRegionDialogue(){$("ul.dropdown-menu.regionMenu li").click(function(){closeRegionList();var clickedText=$(this).find("a").first().text();var clickedCode=$(this).find("a").first().attr("data-regionCode");$("#selectedRegionButton").html(clickedText+' <span class="caret"></span>');$("ul.dropdown-menu.regionMenu li a").removeClass("selected");$("ul.dropdown-menu.regionMenu li a").each(function(){if($(this).attr("data-regionCode")==clickedCode)$(this).addClass("selected");});getDestinationsList();});}
function getLoadingHtml(){var loading='<div class="col-md-12 col-xs-12 text-center" id="loadingResults">'+
'<img src="../res/images/loading.gif" style="width:100px;" />'+
'<p class="msregular">Loading, please wait...</p></div>';return loading;}
function initFullWeekendMap(zoom){var styles=[{"featureType":"water","stylers":[{"color":"#7fc8ed"}]},{"featureType":"landscape","stylers":[{"visibility":"on"},{color:"#f8f7f7"}]},{"featureType":"poi","stylers":[{"visibility":"off"}]},{"featureType":"administrative.country","stylers":[{"visibility":"off"}]},{"featureType":"administrative.province","stylers":[{"visibility":"off"}]},{"featureType":"administrative.locality","stylers":[{"visibility":"on"},{"hue":"#666"},{"saturation":0},{"lightness":60}]},{"featureType":"road","stylers":[{"visibility":"off"}]}];var lat=parseFloat($(".selected").attr("data-lat"));var lng=parseFloat($(".selected").attr("data-lng"));var placeName=$(".selected").attr("data-placeName");var map=new google.maps.Map(document.getElementById('googleMapContainer'),{center:{lat:lat,lng:lng},scrollwheel:false,zoom:zoom});map.setOptions({styles:styles});var infoWindow=new google.maps.InfoWindow();var eventLabel="\""+$("#pageType").val()+"\"";var centerMarker="your_location.png";var cityMarker=new google.maps.Marker({position:new google.maps.LatLng(lat,lng),icon:new google.maps.MarkerImage(domainRoot+"/res/images/map_icons/"+centerMarker,null,null,null,new google.maps.Size(23,30))});cityMarker.setMap(map);$(".dataHolder").each(function(){var thisName=$(this).attr("data-name");var thisCode=$(this).attr("data-code");var thisLat=$(this).attr("data-lat");var thisLng=$(this).attr("data-lng");var thisMarker=$(this).attr("data-marker");var cityMarker=new google.maps.Marker({position:new google.maps.LatLng(thisLat,thisLng),icon:new google.maps.MarkerImage(domainRoot+"/res/images/map_icons/"+thisMarker,null,null,null,new google.maps.Size(25,30))});cityMarker.setMap(map);var thisUrl=$(this).attr("data-url");var thisImg=$(this).attr("data-img");var thisDist=$(this).attr("data-dist");var thisRating=$(this).attr("data-rating");var thisText=$(this).attr("data-text");var contentString='<div class="infoWindow" > <a class="infoWindowLink" target="_blank" href="'+domainRoot+thisUrl+'">'+'<span class="infoName">'+thisName+'</span> '+
thisImg+thisRating+thisText+placeName+'</span><br><br><span class="readMore" style="display:inline">Read About '+thisName.split(",")[0]+'</span></a><div>';cityMarker.addListener('click',function(){trackGAEvent("MapviewTracking","MapIconClicked",$("#pageType").val());infoWindow.setContent(contentString);infoWindow.open(map,cityMarker);});});}
var map;var markers=[];var infoWindow;function clearMarkers(){for(var i=0;i<markers.length;i++){markers[i].setMap(null);}
markers=[];}
function placeMarkers(){$(".dataHolder").each(function(){var thisName=$(this).attr("data-name");var thisCode=$(this).attr("data-code");var thisLat=$(this).attr("data-lat");var thisLng=$(this).attr("data-lng");var thisMarker=$(this).attr("data-marker");var cityMarker=new google.maps.Marker({position:new google.maps.LatLng(thisLat,thisLng),icon:new google.maps.MarkerImage(domainRoot+"/res/images/map_icons/"+thisMarker,null,null,null,new google.maps.Size(25,30))});cityMarker.setMap(map);markers.push(cityMarker);var thisUrl=$(this).attr("data-url");var thisImg=$(this).attr("data-img");var thisRating=$(this).attr("data-rating");var thisText=$(this).attr("data-text");thisText=thisText.split(/\s+/).slice(0,23).join(" ")+"...";var thisDist=$(this).attr("data-dist");var contentString='<div class="infoWindow" > <a class="infoWindowLink" target="_blank" href="'+domainRoot+thisUrl+'">'+'<span class="infoName">'+thisName+'</span> '+
thisImg+thisRating+thisText+'<br><span class="readMore" >Read More</span></a><div>';cityMarker.addListener('click',function(){infoWindow.setContent(contentString);infoWindow.open(map,cityMarker);});});}
function CenterControl(controlDiv,map){var controlUI=document.createElement('div');controlUI.style.backgroundColor='#fff';controlUI.style.border='2px solid #fff';controlUI.style.borderRadius='3px';controlUI.style.boxShadow='0 2px 6px rgba(0,0,0,.3)';controlUI.style.cursor='pointer';controlUI.style.marginBottom='22px';controlUI.style.marginTop='5px';controlUI.style.textAlign='center';controlUI.title='Click to disable show as I move the map';controlDiv.appendChild(controlUI);var controlText=document.createElement('div');controlText.style.color='rgb(25,25,25)';controlText.style.fontFamily='Roboto,Arial,sans-serif';controlText.style.fontSize='16px';controlText.style.lineHeight='38px';controlText.style.paddingLeft='5px';controlText.style.paddingRight='5px';controlText.innerHTML='Disable show as I move?';controlUI.appendChild(controlText);controlUI.addEventListener('click',function(){if(controlText.innerHTML=='Disable show as I move?')
{controlText.innerHTML='Disabled';$('#mapFilter').val("no");}
else
{controlText.innerHTML='Disable show as I move?';$('#mapFilter').val("yes");}});}
function initFullExploreMap(zoom){var styles=[{"featureType":"water","stylers":[{"color":"#7fc8ed"}]},{"featureType":"landscape","stylers":[{"visibility":"on"},{color:"#f8f7f7"}]},{"featureType":"poi","stylers":[{"visibility":"off"}]},{"featureType":"administrative.country","stylers":[{"visibility":"off"}]},{"featureType":"administrative.province","stylers":[{"visibility":"off"}]},{"featureType":"administrative.locality","stylers":[{"visibility":"on"},{"hue":"#666"},{"saturation":0},{"lightness":60}]},{"featureType":"road","stylers":[{"visibility":"off"}]}];var lat=parseFloat("21.146633");var lng=parseFloat("79.088860");map=new google.maps.Map(document.getElementById('googleMapContainer'),{center:{lat:lat,lng:lng},scrollwheel:false,zoom:zoom});map.setOptions({styles:styles});infoWindow=new google.maps.InfoWindow();var centerMarker="your_location.png";var cityMarker=new google.maps.Marker({position:new google.maps.LatLng(lat,lng),icon:new google.maps.MarkerImage(domainRoot+"/res/images/map_icons/"+centerMarker,null,null,null,new google.maps.Size(23,30))});cityMarker.setMap(map);placeMarkers();google.maps.event.addListener(map,'idle',function(){var right=map.getBounds().getNorthEast().lng();var left=map.getBounds().getSouthWest().lng();var top=map.getBounds().getNorthEast().lat();var bottom=map.getBounds().getSouthWest().lat();if($('#mapFilter').val()!="no"){var mapBox=top+","+bottom+","+right+","+left;$('#mapBox').val(mapBox);$("#mapLoading").html(getLoadingHtml());$('#translucentLoading').css('display','block');getDestinationsList();}});var centerControlDiv=document.createElement('div');var centerControl=new CenterControl(centerControlDiv,map);centerControlDiv.index=1;map.controls[google.maps.ControlPosition.TOP_CENTER].push(centerControlDiv);}
function openRegionList(){document.getElementById("filterDropDown").classList.toggle("show");}
function closeRegionList(){var dropdowns=document.getElementsByClassName("dropdown-content");var i;for(i=0;i<dropdowns.length;i++){var openDropdown=dropdowns[i];if(openDropdown.classList.contains('show')){openDropdown.classList.remove('show');}}}
$(function(){enableSlider();enableFilters();enableSelectOriginDialogue();enableSelectRegionDialogue();$("img.resultImage.lazy").lazyload({effect:"fadeIn"});var initialPlaceCode=$("#initialPlaceCode").val();if(initialPlaceCode!="NEAR-ME"){$(".startingPlaceMenu li a").each(function(){if($(this).attr("data-placeCode")==initialPlaceCode)$(this).addClass("selected");});}});